Repository DPII-24-25/Acme-ANS-D, pull requests merged in 2025-03, with the labels that each got.

#51 flight crew member done
  src/main/java/acme/realms/FlightCrewAvailability.java
  src/main/java/acme/realms/FlightCrewMember.java
Labels: enhancement

#56 G-R07: Add service entity
  src/main/java/acme/entities/Service.java
Labels: mandatory

#46 S05-R03: Create Technician Entity
  src/main/java/acme/realms/Technician.java
Labels: enhancement, mandatory

#54 S04-R03: Assistance agent
  src/main/java/acme/realms/AssistanceAgent.java
Labels: mandatory

#63 S03- R03 : Validations done
  src/main/java/acme/constraints/FlightCrewMemberValidator.java
  src/main/java/acme/constraints/ValidFlightCrewMember.java
  src/main/java/acme/realms/FlightCrewMember.java
  src/main/java/acme/realms/FlightCrewMemberRepository.java
Labels: enhancement

#36 S05-R16: Create UML Domain Model-Student-5.uxf
  reports/Student5/UML Domain Model-Student-5.uxf
Labels: documentation

#62 G-R05: Airline Entity Added
  src/main/java/acme/entities/airline/Airline.java
  src/main/java/acme/entities/airline/AirlineType.java
  src/main/resources/WEB-INF/data/sample/airline.csv
Labels: mandatory

#55 S04-R04: Claim entity
  src/main/java/acme/constraints/AssistanceAgentValidator.java
  src/main/java/acme/constraints/ClaimValidator.java
  src/main/java/acme/constraints/ServiceValidator.java
  src/main/java/acme/constraints/ValidAssistanceAgent.java
  src/main/java/acme/constraints/ValidClaim.java
  src/main/java/acme/constraints/ValidService.java
  src/main/java/acme/entities/claim/Claim.java
  src/main/java/acme/entities/claim/ClaimRepository.java
  src/main/java/acme/entities/claim/IssuesType.java
  src/main/java/acme/entities/service/Service.java
  src/main/java/acme/entities/service/ServiceRepository.java
  src/main/java/acme/realms/assistanceAgent/AssistanceAgent.java
  src/main/java/acme/realms/assistanceAgent/AssistanceAgentRepository.java
Labels: mandatory

#50 feature aircraft entity done
  src/main/java/acme/constraints/AircraftValidator.java
  src/main/java/acme/constraints/ValidAircraft.java
  src/main/java/acme/entities/aircraft/Aircraft.java
  src/main/java/acme/entities/aircraft/AircraftRepository.java
  src/main/java/acme/entities/aircraft/AircraftStatus.java
Labels: enhancement, mandatory

#52 Flight assignment done
  src/main/java/acme/constraints/FlightAssignmentValidator.java
  src/main/java/acme/constraints/ValidFlightAssignment.java
  src/main/java/acme/entities/flightAssignment/FlightAssignment.java
  src/main/java/acme/entities/flightAssignment/FlightAssignmentRepository.java
  src/main/java/acme/entities/flightAssignment/FlightAssignmentStatus.java
  src/main/java/acme/entities/flightAssignment/FlightCrewDuty.java
Labels: enhancement, mandatory

#64 Activity Log entity done with correspondints validations and repository
  src/main/java/acme/constraints/ActivityLogValidator.java
  src/main/java/acme/constraints/ValidActivityLog.java
  src/main/java/acme/entities/activityLog/ActivityLog.java
  src/main/java/acme/entities/activityLog/ActivityLogRepository.java
Labels: enhancement, mandatory

#61 S02-R03,04,05,06
  src/main/java/acme/constraints/CreditCardValidator.java
  src/main/java/acme/constraints/ValidDigitsCreditCard.java
  src/main/java/acme/entities/customers/Booking.java
  src/main/java/acme/entities/customers/BookingRepository.java
  src/main/java/acme/entities/customers/Passenger.java
  src/main/java/acme/entities/customers/TravelClass.java
  src/main/java/acme/realms/Customer.java
  src/main/resources/WEB-INF/data/sample/booking.csv
  src/main/resources/WEB-INF/data/sample/customer.csv
  src/main/resources/WEB-INF/data/sample/passenger.csv
  src/main/resources/WEB-INF/data/sample/user-account.csv
Labels: mandatory

#35 G-R26 : Create UML Domain Model-Group
  reports/Group/D02/UML Domain Model-Group.uxf
Labels: documentation
